{{- range $version, $config := .Values.versions }}
{{- if $config.enabled }}
---
apiVersion: unleash.nais.io/v1
kind: ReleaseChannel
metadata:
  name: unleash-{{ $version }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    {{- include "unleash-releasechannel.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $version }}
spec:
  image: {{ include "unleash-releasechannel.image" (dict "registry" $.Values.image.registry "repository" $.Values.image.repository "tag" $config.tag) | quote }}
  strategy:
    maxParallel: {{ $config.strategy.maxParallel | default $.Values.strategy.maxParallel }}
    {{- $batchInterval := $config.strategy.batchInterval | default $.Values.strategy.batchInterval }}
    {{- if $batchInterval }}
    batchInterval: {{ $batchInterval | quote }}
    {{- end }}
    {{- $canary := $config.strategy.canary | default $.Values.strategy.canary }}
    {{- if $canary.enabled }}
    canary:
      enabled: true
      {{- if $canary.labelSelector }}
      podSelector:
        {{- toYaml $canary.labelSelector | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if $config.maxUpgradeTime }}
    maxUpgradeTime: {{ $config.maxUpgradeTime | quote }}
    {{- end }}
  {{- $healthChecks := $config.healthChecks | default $.Values.healthChecks }}
  {{- if $healthChecks.enabled }}
  healthChecks:
    enabled: {{ $healthChecks.enabled }}
    {{- if $healthChecks.initialDelay }}
    initialDelay: {{ $healthChecks.initialDelay | quote }}
    {{- end }}
    {{- if $healthChecks.timeout }}
    timeout: {{ $healthChecks.timeout | quote }}
    {{- end }}
  {{- end }}
  {{- if $config.breakGlassTargetTag }}
  {{- if ne $config.breakGlassTargetTag $config.tag }}
  {{- fail (printf "versions.%s.breakGlassTargetTag must equal versions.%s.tag" $version $version) }}
  {{- end }}
  breakGlassImage: {{ include "unleash-releasechannel.image" (dict "registry" $.Values.image.registry "repository" $.Values.image.repository "tag" $config.breakGlassTargetTag) | quote }}
  {{- end }}
  {{- if $config.allowDowngrade }}
  allowDowngrade: true
  {{- end }}
  {{- if $.Values.rollback.enabled }}
  rollback:
    enabled: {{ $.Values.rollback.enabled }}
    onFailure: {{ $.Values.rollback.onFailure }}
  {{- end }}
{{- end }}
{{- end }}
