# vi: se sts=2 ts=2 sw=2 et:

language: node_js

sudo: required

services:
  - docker

before_install:
  - docker build -t navikt/unleash .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push navikt/unleash
