# vi: se sts=2 ts=2 sw=2 et:

sudo: required

services:
  - docker

before_install:
  - docker build -t navikt/unleash:$TRAVIS_BRANCH .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push navikt/unleash:$TRAVIS_BRANCH;
    fi
