# vi: se sts=2 ts=2 sw=2 et:

language: generic

sudo: required

services:
  - docker

script:
  - export RELEASE_VERSION="$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')"
  - export DOCKER_IMAGE_FULL_NAME="$TRAVIS_REPO_SLUG:$RELEASE_VERSION"
  - docker build -t "$DOCKER_IMAGE_FULL_NAME" .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push "$DOCKER_IMAGE_FULL_NAME";
      git remote add auth-origin "https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}";
      git tag "$RELEASE_VERSION";
      git push auth-origin --tags;
    fi
