# vi: se sts=2 ts=2 sw=2 et:

language: generic

sudo: required

services:
  - docker

before_install:
  - export TAGGED_VERSION="$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')"
  - docker build -t navikt/unleash:latest -t navikt/unleash:$TAGGED_VERSION .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push navikt/unleash:latest
  - docker push navikt/unleash:$TAGGED_VERSION
