# vi: se sts=2 ts=2 sw=2 et:

language: generic

sudo: required

services:
  - docker

before_install:
  - docker build .

after_success:
  - git tag "$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')"
  - git remote add auth-origin https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  - git push auth-origin --tags
