# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/pus/unleash
replicas:
  min: 1
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: /
  readiness:
    path: /
fasitResources:
  used:
  - alias: unleash-pg
    resourceType: datasource
  - alias: ldap
    resourceType: ldap
  - alias: unleash-azuread
    resourceType: applicationProperties
  exposed:
  - alias: unleash-api
    resourceType: restservice
    path: /api/
