# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/pus/unleash
team: pus
replicas:
  min: 2
  max: 8
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: /
  readiness:
    path: /
resources:
  limits:
    cpu: 1
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi
fasitResources:
  used:
  - alias: unleash-pg
    resourceType: datasource
  - alias: unleash-azuread
    resourceType: applicationProperties
  exposed:
  - alias: unleash-apigw
    resourceType: restservice
    path: /api

alertProfiles:
  - basic