---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: unleash
  namespace: default
  labels:
    team: dataplattform
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://unleash.nais.adeo.no
    - https://unleash.nais.preprod.local
  liveness:
    path: /
  readiness:
    path: /
  prometheus:
    enabled: true
    path: internal-backstage/prometheus
  replicas:
    min: 2
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
