apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: unleash
  namespace: aura
  labels:
    team: aura
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#ingresses}}
     - {{.}}
  {{/ingresses}}
  liveness:
    path: /
  readiness:
    path: /health
  prometheus:
    enabled: true
    path: /internal-backstage/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 85
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 500m
      memory: 512Mi
  envFrom:
    - secret: unleash
  gcp:
    sqlInstances:
      - name: unleash
        type: POSTGRES_11
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: unleash
            envVarPrefix: DB
  webproxy: true
