apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: unleash
  namespace: aura
  labels:
    team: aura
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "64Mi"
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#ingresses}}
     - {{.}}
  {{/ingresses}}
  liveness:
    path: /
  readiness:
    path: /health
  prometheus:
    enabled: true
    path: /internal-backstage/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 85
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 250m
      memory: 200Mi
  envFrom:
    - secret: unleash
  gcp:
    sqlInstances:
      - name: {{database.name}}
        type: {{database.type}}
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: unleash
            envVarPrefix: DB
