---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: unleash
  namespace: {{namespace}}
  labels:
    team: dataplattform
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /
  readiness:
    path: /
  prometheus:
    enabled: true
    path: /internal-backstage/prometheus
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 85
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
  webproxy: true
