name: Build, push, and sign image
on:
  push:
    branches:
      - unleash-v4

jobs:
  build_push_sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@add-extra-tags
        with:
          name: unleash-v4
          dockerfile: Dockerfile
          google_service_account: gh-unleash
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
